/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./**/*.{html,js,jsx,ts,tsx,vue,svelte}'],
    theme: {
        extend: {
            colors: {
                // ── BRAND COLOR ──────────────────────────────────────────────────
                // Generated by Ken Design System. Brand hex: #0d4891
                // Scale is APCA-compliant: 600 achieves |Lc| ≥ 75 vs white (body text).
                // ─────────────────────────────────────────────────────────────────
                primary: {
                    50: '#ecf0f5',
                    100: '#dee7f3',
                    200: '#c7d9f0',
                    300: '#abc9ef',
                    400: '#86b5ef',
                    500: '#589bed',
                    600: '#0d4891',
                    700: '#10417f',
                    800: '#143b6c',
                    900: '#193557',
                },
                neutral: {
                    0: '#ffffff', 50: '#f8fafc', 100: '#f1f5f9', 200: '#e2e8f0',
                    300: '#cbd5e1', 400: '#94a3b8', 500: '#64748b', 600: '#475569',
                    700: '#334155', 800: '#1e293b', 900: '#111827', 950: '#0a1120',
                    // Cool blue-gray — Tailwind slate 50-800, gray-900 for body text
                },
                success: { 50: '#f0fdf4', 100: '#dcfce7', 200: '#bbf7d0', 500: '#22c55e', 600: '#16a34a', 700: '#15803d' },
                warning: { 50: '#fffbeb', 100: '#fef3c7', 200: '#fde68a', 500: '#f59e0b', 600: '#d97706', 700: '#b45309' },
                danger: { 50: '#fef2f2', 100: '#fee2e2', 200: '#fecaca', 500: '#ef4444', 600: '#dc2626', 700: '#b91c1c', 800: '#991b1b' },
            },
            fontFamily: {
                sans: ['-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Helvetica', 'Arial', 'sans-serif'],
                mono: ['"SFMono-Regular"', 'Consolas', '"Liberation Mono"', 'Menlo', 'monospace'],
            },
            borderRadius: { none: '0', sm: '3px', DEFAULT: '6px', md: '6px', lg: '8px', xl: '12px', '2xl': '16px', full: '9999px' },
            boxShadow: {
                sm: '0 0 0 1px rgba(15,23,42,0.04),0 1px 2px -0.5px rgba(15,23,42,0.06),0 2px 4px rgba(15,23,42,0.035)',
                DEFAULT: '0 0 0 1px rgba(15,23,42,0.05),0 2px 4px -1px rgba(15,23,42,0.06),0 4px 8px rgba(15,23,42,0.045)',
                md: '0 0 0 1px rgba(15,23,42,0.05),0 4px 8px -2px rgba(15,23,42,0.08),0 8px 16px rgba(15,23,42,0.055)',
                lg: '0 0 0 1px rgba(15,23,42,0.05),0 8px 16px -4px rgba(15,23,42,0.10),0 16px 32px rgba(15,23,42,0.07)',
                xl: '0 0 0 1px rgba(15,23,42,0.04),0 16px 32px -8px rgba(15,23,42,0.12),0 32px 64px rgba(15,23,42,0.08)',
                inset: 'inset 0 1px 2px rgba(15,23,42,0.06)',
                none: 'none',
            },
        },
    },
    plugins: [],
}